/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DaiContract } from "./DaiContract";
export * as factories from "./factories";
export { DaiContract__factory } from "./factories/DaiContract__factory";
